POST http://127.0.0.1:3003/api/auth/registro
Content-Type: application/json
Accept: application/json

{
  "nombres":"Carlos Luis",
  "apellidos":"Parraga Vera",
  "email":"carlinparraga@gmail.com",
  "password":"Carlin$12345"
}

###login
POST http://127.0.0.1:3005/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "email":"cparraga1@coopcalcetaltda.fin.ec",
  "password":"Carlin$12345"
}